tap "homebrew/cask"
tap "buo/cask-upgrade"
brew "mas"
tap "homebrew/cask-fonts"
tap "buo/cask-upgrade"

brew "git"
brew "awscli"
brew "nvim"
brew "starship"
brew "snappy"
brew "rustup-init"
brew "pyenv"
brew "pyenv-virtualenv"
brew "jq"
brew "pandoc"
brew "chezmoi" # Terminal configuration management
brew "pipx" 
brew "nushell" # Data centric shell written in rust
brew "make"
brew "docker"
brew "eza"
brew "dust"
brew "copier"
brew "bat"
cask "tabby"
cask "font-hasklug-nerd-font"
cask "font-monoid-nerd-font"
cask "visual-studio-code" # IDE
cask "obsidian" # Notes written in Markdown
cask "rectangle" # Move windows with keyboard shortcuts
