"$schema" = 'https://starship.rs/config-schema.json'

palette = 'onehalf_dark'


format = """
[](c_user)\
$username\
[](fg:c_user bg:c_shell)\
$shell\
$directory\
[](fg:c_shell bg:c_git)\
$git_branch\
$git_status\
[](fg:c_git bg:c_lang)\
$nodejs\
$rust\
$python\
[](fg:c_lang)\
$line_break\
[ ](fg:#bfceff) 
"""

# Disable the blank line at the start of the prompt
add_newline = false

[palettes.onehalf_dark]
c_red = '#e45649'
c_lang = '#50a14f'
c_shell = '#c18401'
c_user = '#0184bc'
c_purple = '#a626a4'
c_git = '#0997b3'
c_fg = '#383a42'
c_bg = '#fafafa'
c_comment = '#a0a1a7'
c_selection = '#bfceff'

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:c_user"
style_root = "bg:c_user"
format = '[$user ]($style)'

[directory]
style = "bg:c_shell"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:c_git"
format = '[[ $symbol $branch ](bg:c_git)]($style)'

[git_status]
style = "bg:c_git"
format = '[[($all_status$ahead_behind )](bg:c_git)]($style)'

[nodejs]
symbol = ""
style = "bg:c_lang"
format = '[[ $symbol ($version) ](bg:c_lang)]($style)'

[rust]
symbol = ""
style = "bg:c_lang"
format = '[[ $symbol ($version) ](bg:c_lang)]($style)'

[python]
style = "bg:c_lang"
format = '[[ $symbol ($version)](bg:c_lang)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'

[shell]
disabled = false
format = "[$indicator](bg:c_shell)"
